# The first instruction is what image we want to base our container on
# We Use an official Python runtime as a parent image
#FROM python:3.6-alpine
FROM python:3.6.4
# The enviroment variable ensures that the python output is set straight
# to the terminal with out buffering it first
ENV PYTHONUNBUFFERED 1

# create root directory for our project in the container
RUN mkdir /home_banking_service

# Set the working directory to /home_banking_service
WORKDIR /home_banking_service
# Transferring requirement file so that pip install image will be cached and whenever source code will change it wont need to make this image again
ADD ./requirements.txt  /home_banking_service/

# Install any needed packages specified in requirements.txt
RUN pip install -r requirements.txt

# Copy the current directory contents into the container at /home_banking_service
ADD . /home_banking_service/

RUN python manage.py makemigrations customer && python manage.py makemigrations account && python manage.py makemigrations payments && python manage.py migrate
