# Generated by Django 2.0.7 on 2018-07-07 18:22

import computed_property.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customerDetailsManagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankcustomer',
            name='coordinate',
            field=computed_property.fields.ComputedCharField(blank=True, compute_from='calculate_coordinates', editable=False, max_length=192),
        ),
    ]
