# Generated by Django 2.0.7 on 2018-07-07 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerDetailsManagement', '0002_bankcustomer_coordinate'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditTransfer',
            fields=[
                ('transfer_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('originator_customer_id', models.IntegerField()),
                ('originator_acc_number', models.IntegerField()),
                ('transfer_amount', models.FloatField()),
                ('beneficiary_customer_id', models.IntegerField()),
                ('beneficary_acc_number', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='bankaccount',
            name='id',
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='acc_number',
            field=models.IntegerField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
