# Generated by Django 2.0.7 on 2018-07-09 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerDetailsManagement', '0003_auto_20180707_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='acc_number',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
