# Generated by Django 2.0.7 on 2018-07-09 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerDetailsManagement', '0004_auto_20180709_1718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credittransfer',
            name='transfer_id',
        ),
        migrations.AddField(
            model_name='credittransfer',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
