# Generated by Django 2.0.7 on 2018-07-09 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customerDetailsManagement', '0005_auto_20180709_1903'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankaccount',
            old_name='customer_id',
            new_name='customer',
        ),
    ]
