# Generated by Django 2.0.7 on 2018-07-09 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customerDetailsManagement', '0006_auto_20180709_2041'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankaccount',
            old_name='customer',
            new_name='customer_id',
        ),
    ]
