# Generated by Django 2.0.7 on 2018-07-10 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customerDetailsManagement', '0007_auto_20180709_2045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankaccount',
            name='acc_type',
        ),
    ]
