# Generated by Django 2.0.7 on 2018-07-10 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerDetailsManagement', '0008_remove_bankaccount_acc_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='acc_type',
            field=models.CharField(choices=[('Credit_card', 'Credit_card'), ('Debit_card', 'Debit_card')], default='Credit_card', max_length=20),
            preserve_default=False,
        ),
    ]
