# Generated by Django 2.0.7 on 2018-07-10 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerDetailsManagement', '0009_bankaccount_acc_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='acc_type',
            field=models.CharField(choices=[('Credit_Card', 'Credit_Card'), ('Debit_Card', 'Debit_Card')], max_length=20),
        ),
    ]
